TITLE EXAMPLE PROGRAM
STACK SEGMENT STACK
	DW 64 DUP(?)
STACK ENDS
DATA SEGMENT 
	NET DW ?
	SAVE DW ?
	TOTAL DW ?
	UNIT DB 101
DATA ENDS
CODE SEGMENT 
	ASSUME CS:CODE, DS:DATA, SS:STACK
FIRST PROC
	MOV AX,DATA ; AX = DATA
	MOV DS,AX ; DS = AX
	MOV BX,39  ; BX = 39
	MOV AX,BX ; AX = BX
	MUL UNIT ; AX = AX*UNIT
	MOV NET,AX ; NET = AX
	MOV AL,UNIT ; AL = UNIT
	CBW
	MOV CX,4 ; CX = 4  
	DIV CX ; AX = AX/CX
	MUL BX ; AX = BX * AX
	MOV SAVE,AX ; SAVE = AX
	MOV AX,NET ; AX = NET 
	SUB AX,SAVE ; AX = SAVE
	MOV TOTAL,AX ; TOTAL = AX
	MOV AH,4CH 
	INT 21H
FIRST ENDP
CODE ENDS
	END FIRST
	